config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :scores
  get 'scores/index'
  root "scores#index"

  post 'scores/post_data' => 'scores#edit'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/score.rb
class Score < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:GolfCourse, :GolfAddress)
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]

  # GET /scores or /scores.json
  def index
    @scores = Score.all
  #  scores = Score.select('play_date,golf_couse')

    respond_to do |format|
      format.html
      format.json {render :json => @scores}
    end
  end

  # GET /scores/1 or /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores or /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: "Score was successfully created." }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end
  #POST /post_data
  def post_data
    if parames("oper") == "add"
      score = score.new
    end
    score.play_date = params("play_data")
  
  end
  
  # PATCH/PUT /scores/1 or /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: "Score was successfully updated." }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1 or /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: "Score was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:play_date, :golf_couse, :out_score, :out_pats, :in_score, :in_pats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="course">
    <tr>
      <%= form.label "ゴルフ場" %>
      <%= form.text_field :GolfCourse %>
    </tr>
  </table>

  <br>
  <div class="field">
    <%= form.label "住所" %>
    <%= form.text_area :GolfAddress %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>ゴルフ場 編集</h1>

<%= render 'form', course: @course %>

<%= button_to '詳細', @course, method: :get%>
<%= button_to '戻る', courses_path() %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ゴルフ場 一覧</h1>

<table>
  <thead>
    <tr>
      <th>コース名</th>
      <th>住所</th>
      <th colspan="3">処理</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.GolfCourse %></td>
        <td><%= course.GolfAddress %></td>
        <td><%= button_to '詳細', course_path(course), method: :get %></td>
        <td><%= button_to '編集', edit_course_path(course), method: :get %></td>
        <td><%= button_to '削除', course, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<br>
<%= button_to '新規登録', new_course_path(), method: :get %>
<%= button_to '戻る', {controller: 'scores', action: 'index'}, {method: :get} %>
<br>

<!-- footer -->
  <footer>
　　<ul class="footer-menu">
     <li>home ｜</li>
     <li>about ｜</li>
     <li>service ｜</li>
     <li>Contact Us</li>
    </ul>
    <p>© All rights reserved by SumitomoTeshima</p>
  </footer>

app/views/courses/new.html.erb
<h1>ゴルフ場 新規登録</h1>

<%= render 'form', course: @course %>

<%= button_to '戻る', courses_path(), method: :get %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<h1>ゴルフ場 詳細</h1>

<table class = "course">
  <tbody>
    <tr>
      <th class = "arrow_box" > ゴルフ場：</th>
      <td> <%= @course.GolfCourse %> </td>
    </tr>
    <tr>
      <th class = "arrow_box" > 住所　　：</th>
      <td> <%= @course.GolfAddress %> </td>
    </tr>
  </tbody>
</table>

<br>

<br>

<%= button_to '編集', edit_course_path(@course), method: :get %>
<%= button_to '戻る', courses_path(), method: :get %>

<!-- footer -->
  <footer>
　　<ul class="footer-menu">
     <li>home ｜</li>
     <li>about ｜</li>
     <li>service ｜</li>
     <li>Contact Us</li>
    </ul>
    <p>© All rights reserved by SumitomoTeshima</p>
  </footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GolfScore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_with(model: score) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :プレー日 %>
    <%= form.date_select :play_date %>
  </div>

  <div class="field">
    <%= form.label :ゴルフコース %>
    <%= form.text_field :golf_couse %>
  </div>

  <div class="field">
    <%= form.label :前半スコア %>
    <%= form.text_field :out_score %>
  </div>

  <div class="field">
    <%= form.label :前半パット数 %>
    <%= form.text_field :out_pats %>
  </div>

  <div class="field">
    <%= form.label :後半スコア %>
    <%= form.text_field :in_score %>
  </div>

  <div class="field">
    <%= form.label :後半パット数 %>
    <%= form.text_field :in_pats %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>スコアの修正</h1>

<%= render 'form', score: @score %>

<%= link_to '参照', @score %> |
<%= link_to '戻る', scores_path %>

app/views/scores/index.html.erb
<h1>ゴルフスコアを管理します。</h1>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.15.5/jquery.jqgrid.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/themes/redmond/jquery-ui.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.15.5/css/ui.jqgrid.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/free-jqgrid/4.15.5/plugins/css/ui.multiselect.min.css"/>

<body>

  <table id="score_list"></table>
  <div id="pager"></div>
  <br>
  <%= button_to 'ゴルフコースを登録', courses_path, method: :get %>

</body>


<script>
  $(function(){
    // ユーザー設定 - ゴルフスコア
    $('#score_list').jqGrid({
      url:'/scores/',
      datatype:'json',
      colNames:[" ","プレー日","コース名","アウト","パット","イン","パット"],
      colModel:[
        {bame:'myac',width:50,fixed:true,sortable:false,resize:false,
          formatter:'actions',formatoptions:{keys:true}},
        {name:'play_date',width:100,align:'center',sortable:true,editable:true},
        {name:'golf_couse',width:300,align:'left',sortable:true,editable:true},
        {name:'out_score',width:50,align:'right',sortable:true,editable:true},
        {name:'out_pats',width:50,align:'right',sortable:true,editable:true},
        {name:'in_score',width:50,align:'right',sortable:true,editable:true},
        {name:'in_pats',width:50,align:'right',sortable:true,editable:true}
      ],
      width:'auto',
      height:'auto',
      sortname:'play_data',
      sortorder:"ASC",
      multiselect: false,
      caption:"ゴルフスコア",
      pager:'#pager',
      editurl:"scores/post_data"
    });
    $("#score_list").jqGrid("navGrid","#pager",
      {view:true,edit:false,add:true,del:false}, // options
      {}, // edit options
      {height:290,jqModal:false, closeOnEscape:true,bottominfo:"Fields marked with (*) are required", closeAfterAdd: true}, // add options
      {}, // del options
      {closeOnEscape:true}, // search options
      {height:250,jqModal:false,closeOnEscape:true} // view options
    );
  });
  $(function() {
    $("input[type='button']").button();
  });

</script>

app/views/scores/new.html.erb
<h1>新しいスコアを登録します。</h1>

<%= render 'form', score: @score %>

<%= link_to '戻る', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>プレー日:</strong>
  <%= @score.play_date %>
</p>
<p>
  <strong>ゴルフコース:</strong>
  <%= @score.golf_couse %>
</p>
<p>
  <strong>前半スコア:</strong>
  <%= @score.out_score %>
</p>
<p>
  <strong>前半パット数:</strong>
  <%= @score.out_pats %>
</p>
<p>
  <strong>後半スコア:</strong>
  <%= @score.in_score %>
</p>
<p>
  <strong>後半パット数:</strong>
  <%= @score.in_pats %>
</p>

<%= link_to '編集', edit_score_path(@score) %> |
<%= link_to '戻る', scores_path %>